changelog:
  sections:
  - title: "Enhancements"
    emoji: ":star:"
    labels: ["new", "enhancements"]
  - title: "Bugs"
    emoji: ":bug:"
    labels: ["fix", "bug"]
  - title: "technical"
    emoji: ":wrench:"
    labels: ["technical"]

  issues:
    exclude:
      labels: ["wontfix", "question", "duplicate", "can't reproduce"]