language: scala

sudo: true

git:
  depth: 1

scala:
  - "2.13.1"

jdk:
  - openjdk11

services:
  - docker

before_install:
  - docker run -d -p 27017:27017 -v $(pwd)/mongo-data:/data/db mongo
  
script:
  - sh ./scripts/build.sh test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.nvm
    - $HOME/.yarn
    - $HOME/.yarn-cache
