version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_daikoku
    networks:
      - basicsetup
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../daikoku/javascript/tests/config/postgres/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    ports:
      - 5432:5432

  otoroshi:
    image: maif/otoroshi:latest
    networks:
      - basicsetup
    environment:
      - OTOROSHI_EXPOSED_PORTS_HTTP=8080
      - OTOROSHI_INITIAL_ADMIN_LOGIN=admin@otoroshi.io
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_IMPORT_FROM=/usr/app/otoroshi/imports/otoroshi-state.json
      - OTOROSHI_DOMAIN=oto.tools
    volumes:
      - "../daikoku/javascript/tests/config/otoroshi:/usr/app/otoroshi/imports"
    ports:
      - 8080:8080

networks:
  basicsetup:
    driver: bridge
    ipam:
      driver: default
