version: "3"
services:
  oidc-server-mock:
    image: ghcr.io/xdev-software/oidc-server-mock:1.0.4
    ports:
      - "9001:8080"
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 2s
      timeout: 10s
      retries: 100
    environment:
      IDENTITY_RESOURCES_INLINE: |
        [ { "Name": "role", "ClaimTypes": ["role"] } ]
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      LOGIN_OPTIONS_INLINE: |
        {
          "AllowRememberLogin": false
        }
      LOGOUT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true,
          "ShowLogoutPrompt": true
        }
      #API_SCOPES_INLINE: |
      #  - Name: some-app-scope-1
      #  - Name: some-app-scope-2
      #API_SCOPES_INLINE: |
      #  [
      #    {
      #      "Name": "roles",
      #      "UserClaims": ["roles"]
      #    }
      #  ]
      #API_RESOURCES_INLINE: |
      #  - Name: roles
      #    Scopes:
      #      - roles
      #      - some-app-scope-2
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"michael.scott@dundermifflin.com",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Michael Scott",
                "ValueType": "string",
              },
              {
                "Type": "role",
                "Value": "admin",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "michael.scott@dundermifflin.com",
                "ValueType": "string"
              }
            ]
          },
          {
            "SubjectId":"2",
            "Username":"jim.halpert@dundermifflin.com",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Jim Halpert",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "jim.halpert@dundermifflin.com",
                "ValueType": "string"
              },
              {
                "Type": "role",
                "Value": "user",
                "ValueType": "string"
              },
              {
                "Type": "role",
                "Value": "manager",
                "ValueType": "string"
              },
              {
                "Type": "role",
                "Value": "saler",
                "ValueType": "string"
              },
              {
                "Type": "birthdate",
                "Value": "1978/10/01",
                "ValueType": "string"
              }
            ]
          },
          {
            "SubjectId":"3",
            "Username":"pam.beesly@dundermifflin.com",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Pam Beesly",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "pam.beesly@dundermifflin.com",
                "ValueType": "string"
              }
            ]
          },
          {
            "SubjectId":"4",
            "Username":"andy.BERNARD@dundermifflin.com",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Andy Bernard",
                "ValueType": "string"
              },
              {
                "Type": "email",
                "Value": "andy.BERNARD@dundermifflin.com",
                "ValueType": "string"
              },
              {
                "Type": "role",
                "Value": "user",
                "ValueType": "string"
              },
            ]
          }
        ]
      CLIENTS_CONFIGURATION_INLINE: |
        [
          {
            "ClientId": "foo",
            "ClientSecrets": ["bar"],
            "Description": "Client for implicit flow",
            "AllowedGrantTypes": ["authorization_code"],
            "RequirePkce": false,
            "AllowOfflineAccess": true,
            "AllowAccessTokensViaBrowser": true,
            "RedirectUris": ["http://localhost:5173/auth/oauth2/callback", "http://localhost:9000/auth/oauth2/callback"],
            "AllowedScopes": ["openid", "profile", "email", "role", "offline_access"],
            "IdentityTokenLifetime": 3600,
            "AccessTokenLifetime": 3600,
            "AlwaysIncludeUserClaimsInIdToken": true,
            "PostLogoutRedirectUris": ["http://localhost:5173/"]
        }
        ]
      ASPNET_SERVICES_OPTIONS_INLINE: |
        {
          "ForwardedHeadersOptions": {
            "ForwardedHeaders" : "All"
          }
        }

  smtp:
    image: reachfive/fake-smtp-server:latest
    networks:
      - basicsetup
    ports:
      - 1080:1080
      - 1025:1025

  redis:
    image: redis:7.2
    networks:
      - basicsetup
    expose:
      - 6379
    ports:
      - 6379:6379

  otoroshi:
    image: maif/otoroshi:latest
    networks:
      - basicsetup
    environment:
      - OTOROSHI_STORAGE=redis
      - OTOROSHI_REDIS_HOST=redis
      - OTOROSHI_EXPOSED_PORTS_HTTP=8080
      - OTOROSHI_INITIAL_ADMIN_LOGIN=admin@otoroshi.io
      - OTOROSHI_INITIAL_ADMIN_PASSWORD=password
      - OTOROSHI_IMPORT_FROM=/usr/app/otoroshi/imports/otoroshi-state.json
      - OTOROSHI_DOMAIN=oto.tools
      - OTOROSHI_NEXT_STATE_SYNC_INTERVAL=2000
    volumes:
      - "../daikoku/javascript/tests/config/otoroshi:/usr/app/otoroshi/imports"
    ports:
      - 8080:8080
    depends_on:
      - redis

networks:
  basicsetup:
    driver: bridge
    ipam:
      driver: default
      # config:
