version: "0.5"

log_level: debug

processes:
  Containers:
    command: "mise run test:front:ldap:containers"
    readiness_probe:
      exec:
        command: "docker inspect daikoku-ldap-test-postgres 2>/dev/null | grep -q '\"Running\": true'"
      initial_delay_seconds: 3
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    shutdown:
      command: "mise run test:front:ldap:clean"
  Backend:
    command: "mise run test:front:ldap:backend"
    is_tty: true
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/health"
        port: 9000
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 100
    depends_on:
      Containers:
        condition: process_healthy
  Frontend:
    command: "mise run dev:front"
    depends_on:
      Containers:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/health"
        port: 5173
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 20
  Tests:
    command: "mise run test:front:ldap:run"
    depends_on:
      Frontend:
        condition: process_healthy
    exit_on_end: true
