version: "0.5"

processes:
  Containers:
    command: "mise run dev:containers"
    readiness_probe:
      http_get:
        host: otoroshi-api.oto.tools
        scheme: http
        path: "/health"
        port: 8080
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 20
    shutdown:
      command: "mise run dev:clean"
  Backend:
    command: "mise run dev:back"
    is_tty: true
    depends_on:
      Containers:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        scheme: http
        path: "/health"
        port: 9000
      initial_delay_seconds: 2
      period_seconds: 5
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 20
  Frontend:
    command: "mise run dev:front"
    depends_on:
      Containers:
        condition: process_healthy
