include "base.conf"

daikoku {
  mode = "dev"
  signingKey = "secret"
  storage = "postgres"
  exposedOn= 5173

  health {
    accessKey = "secret"
  }

  otoroshi {
    sync {
      cron = true
    }
  }

  postgres {
    database = "daikoku"
  }


  tenants {
    provider = "hostname"
  }
}
