name: Playwright tests
on: 
  push:
    paths:
      - 'daikoku/app/**'
      - 'daikoku/javascript/**'
      - '.github/workflows/front-office-tests.yml'
  workflow_dispatch:
  
jobs:
  playwright-run:
    name: playwright run
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: daikoku_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      smtp-server:
        image: reachfive/fake-smtp-server
        ports:
          - 1080:1080
          - 1025:1025
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        # install node lts
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: daikoku/javascript/package-lock.json
    - uses: coursier/cache-action@v6
    - name: initialize backend build
      run: |
        cd daikoku
        sbt  ';clean;compile'
    - name: Installing dependencies
      run: |
        cd daikoku/javascript
        rm -rf node_modules/
        npm ci
    - name: build javascript
      run: |
        cd daikoku/javascript
        npm run build
      env:
        NODE_OPTIONS: --max_old_space_size=4096

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: start backend
      run: |
        cd daikoku
        sbt "bgRun -Ddaikoku.mode=test -Dhttp.port=9000 -Ddaikoku.storage=postgres -Ddaikoku.postgres.database=daikoku_test -Ddaikoku.postgres.user=postgres -Ddaikoku.init.data.from=javascript/cypress/cypress-test-export.ndjson"
    - name: Run tests
      run: |
        cd daikoku/javascript
        npx playwright test --project chromium
