name: Cypress tests
on: [push, pull_request]
  paths:
      - 'daikoku/app/**'
      - 'daikoku/javascript/**'
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    - name: run backend in Background
      id: backend
      run: |
        cd daikoku
        sbt 'run -Dhttp.port=9000 -Ddaikoku.mode=Dev -Ddaikoku.init.data.from=javascript/cypress/cypress-test-export.ndjson' &
    - name: run frontend
      id: run and test frontend
      run: |
        cd daikoku/javascript
        yarn
        yarn start &
        yarn test:cypress