name: Cypress tests
on: 
  push:
    paths:
      - 'daikoku/app/**'
      - 'daikoku/javascript/**'
  pull_request:
    paths:
      - 'daikoku/app/**'
      - 'daikoku/javascript/**'
  workflow_dispatch:
  
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - name: Checkout
      uses: actions/checkout@v2.2.0
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: run backend in Background
      run: |
        cd daikoku
        sbt  'run -Dhttp.port=9000 -Ddaikoku.init.data.from=javascript/cypress/cypress-test-export.ndjson' -Djline.terminal=none < /dev/null &
    - name: install javascript deps
      run: |
        cd daikoku/javascript
        yarn
        yarn build
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        wait-on: 'http://localhost:9000'
        command: yarn test:cypress
        working-directory: daikoku/javascript
      continue-on-error: true
    - name: Copy test execution videos
      if: ${{ failure() }}
      run: |
        mkdir report
        cp -r cypress/videos report/videos
    - name: Merge test results into one
      if: ${{ failure() }}
      run: yarn cypress:report:merge    
    - name: Generate HTML report
      if: ${{ failure() }}
      run: yarn cypress:report:generate
    - name: Commit files
      if: ${{ failure() }}
      run: |
        git config --local user.email "daikoku-github-actions@users.noreply.github.com"
        git config --local user.name "daikoku-github-actions"
        git add --all
        git commit -am "Add cypress tests report"
    - name: Push documentation
      if: ${{ failure() }}
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_TOKEN}}