name: Build
on:
  push:
    paths:
    - 'daikoku/app/**'
    - 'daikoku/test/**'
    

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: daikoku_test
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    # setup java to use sbt
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
    #test DK
    - uses: coursier/cache-action@v6
    - name: test
      id: test
      run: |
        sh ./scripts/build.sh test