name: Build documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: master
    - name: Debug
      run: |
        git checkout master
        git show-ref
        git rev-parse --abbrev-ref HEAD
        git branch
    - name: Generate documentation website
      run: |
        sh ./scripts/build.sh doc
    - name: Push documentation
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add --all
        git commit -am 'Update documentation'
        git push
