name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        wget --quiet https://github.com/sbt/sbt/releases/download/v1.3.3/sbt-1.3.3.zip && unzip $HOME/sbt-1.3.3.zip && rm -f $HOME/sbt-1.3.3.zip
        export PATH=$PATH:/root/sbt/bin
    - name: Generate documentation website
      run: sh ./scripts/build.sh doc
    - name: Push documentation
      run: |
        git commit -am 'Update documentation'
        git push
