name: Build documentations

on:
  push:
    paths:
      - 'manual/**'
    branches:
      - master
    tags:
      - v**
  pull_request:
    paths:
      - 'manual/**'
    branches:
      - master

jobs:
  build_dev_manual:
    name: Build developer documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Generate dev documentation website
        run: sh ./scripts/build.sh devdoc
      - name: Commit files
        run: |
          git config --local user.email "daikoku-github-actions@users.noreply.github.com"
          git config --local user.name "daikoku-github-actions"
          git commit -am "Update dev documentation"
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}
  build_manual:
    name: Build documentation
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Generate documentation website
        run: sh ./scripts/build.sh doc
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Commit files
        run: |
          git config --local user.email "daikoku-github-actions@users.noreply.github.com"
          git config --local user.name "daikoku-github-actions"
          git commit -m "Update documentations for release ${{ steps.get_version.outputs.VERSION }}" -a
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN}}
