name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Debug
      run: ls -ahl
    - name: Generate documentation website
      run: sh ./scripts/build.sh doc
    - name: Push documentation
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git commit -am 'Update documentation'
        git push origin master
